version: '3.3'

services:
  api:
    build: ./backend
    container_name: backend_api
    env_file:
      - .env
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"
    depends_on:
      - database
    restart: unless-stopped


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped


  llm-model:
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    volumes:
      - model:/model
      - huggingface_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    command: >
      --model /model
      --gpu-memory-utilization 0.35
      --reasoning-parser qwen3
    restart: unless-stopped


  llm-agent:
    build: ./LLM_backend
    ports:
      - 8080:8080
    environment:
      - VLLM_API_URL=http://llm-model:8000
      - VLLM_TIMEOUT=120
      - PATH="/home/$USERNAME/.local/bin:$PATH"
      - PYTHONUNBUFFERED=1
    depends_on:
      - llm-model
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  ltm_api:
    build: ./LTM
    ports:
      - "8006:8006"
    environment:
      - PATH="/home/$USERNAME/.local/bin:$PATH"
      - PYTHONUNBUFFERED=1
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - EMBEDDING_MODEL=intfloat/multilingual-e5-large
    depends_on:
      - qdrant
    restart: unless-stopped
    volumes:
      - logs:/app/logs


  tgbot:
    build: ./tg-bot
    env_file:
      - .env
    ports:
      - 8004:8004
    restart: unless-stopped


  image-gen:
    build: ./tbank_imagegen
    restart: unless-stopped

  vlm:
    build: ./vlm
    ports:
      - 8001:8001
    restart: unless-stopped


  database:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5


volumes:
  postgres_data:
  model:
  huggingface_cache:
  logs:
  qdrant_storage: